const {createClient}=window.supabase;const sb=createClient(CAFE_CONFIG.SUPABASE_URL,CAFE_CONFIG.SUPABASE_KEY);let settings={},cats=[],products=[];const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function init(){if(!CAFE_CONFIG.SUPABASE_URL.startsWith('http'))return msg('ابتدا config.js را تنظیم کنید.');const {data:{session}}=await sb.auth.getSession();session?showApp():showLogin()}
function showLogin(){$('login').classList.remove('hidden');$('app').classList.add('hidden')};function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');load()}
async function signIn(){let email=$('email').value.trim(),password=$('password').value;if(!email||!password)return msg('ایمیل و رمز را وارد کنید.');let {error}=await sb.auth.signInWithPassword({email,password});if(error)msg('ورود ناموفق: '+error.message);else showApp()}
async function signOut(){await sb.auth.signOut();showLogin()};function msg(x){$('status').textContent=x}
async function load(){let [s,c,p]=await Promise.all([sb.from('site_settings').select('data').eq('id',1).single(),sb.from('categories').select('*').order('sort_order'),sb.from('products').select('*').order('sort_order')]);if(s.error||c.error||p.error)return msg('خطا در خواندن دیتابیس. SQL را اجرا کنید.');settings=s.data.data||{};cats=c.data||[];products=p.data||[];tab('products')}
function tab(t){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.t===t));if(t==='products')productsTab();if(t==='categories')catsTab();if(t==='home')homeTab();if(t==='brand')brandTab();if(t==='qr')qrTab();if(t==='footer')footerTab();if(t==='appearance')appearanceTab()}
async function saveSettings(data){settings={...settings,...data};let {error}=await sb.from('site_settings').upsert({id:1,data:settings,updated_at:new Date().toISOString()});if(error)msg(error.message);else msg('ذخیره شد.')}
async function upload(file){if(!file)return '';let ext=(file.name.split('.').pop()||'jpg').toLowerCase();let path=Date.now()+'-'+Math.random().toString(36).slice(2)+'.'+ext;let r=await sb.storage.from('menu-images').upload(path,file,{upsert:false});if(r.error)throw r.error;return sb.storage.from('menu-images').getPublicUrl(path).data.publicUrl}
function productsTab(){ $('bodyPanel').innerHTML=`<div class="panel"><h2>آیتم‌ها</h2><button class="primary" onclick="editProduct()">+ افزودن آیتم</button></div><div class="panel">${products.map(p=>`<div class="row"><div><b>${esc(p.name)}</b><small>${Number(p.price).toLocaleString('fa-IR')} تومان ${p.discount?' • '+p.discount+'% تخفیف':''}</small></div><div><button onclick="editProduct(${p.id})">ویرایش</button><button class="danger" onclick="delProduct(${p.id})">حذف</button></div></div>`).join('')}</div>`}
function editProduct(id){let p=id?products.find(x=>x.id===id):{name:'',category_id:cats[0]?.id||'',description:'',price:0,old_price:0,discount:0,image_url:'',featured:false,available:true,sort_order:products.length+1};$('bodyPanel').innerHTML=`<div class="panel"><h2>${id?'ویرایش آیتم':'افزودن آیتم'}</h2><div class="grid2"><label>نام<input id="pn" value="${esc(p.name)}"></label><label>دسته<select id="pc">${cats.map(c=>`<option value="${c.id}" ${c.id===p.category_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>قیمت<input id="pp" type="number" value="${p.price||0}"></label><label>قیمت قبل<input id="po" type="number" value="${p.old_price||0}"></label><label>تخفیف %<input id="pd" type="number" min="0" max="100" value="${p.discount||0}"></label><label>ترتیب<input id="ps" type="number" value="${p.sort_order||0}"></label></div><label>توضیحات<textarea id="px">${esc(p.description||'')}</textarea></label><label>عکس<input id="pi" type="file" accept="image/*"></label><img class="preview" src="${esc(p.image_url||'')}" ${p.image_url?'':'style="display:none"'}><label><input id="pf" type="checkbox" ${p.featured?'checked':''}> ویژه</label><label><input id="pa" type="checkbox" ${p.available!==false?'checked':''}> نمایش در منو</label><div class="actions"><button class="primary" onclick="saveProduct(${id||0})">ذخیره</button><button onclick="productsTab()">انصراف</button></div></div>`}
async function saveProduct(id){try{let old=id?products.find(x=>x.id===id):null,img=old?.image_url||'';if($('pi').files[0])img=await upload($('pi').files[0]);let obj={name:$('pn').value,category_id:$('pc').value,description:$('px').value,price:+$('pp').value,old_price:+$('po').value,discount:+$('pd').value,image_url:img,featured:$('pf').checked,available:$('pa').checked,sort_order:+$('ps').value||0};let r=id?await sb.from('products').update(obj).eq('id',id):await sb.from('products').insert(obj);if(r.error)throw r.error;await load()}catch(e){msg(e.message)}}
async function delProduct(id){if(confirm('حذف شود؟')){let r=await sb.from('products').delete().eq('id',id);if(r.error)msg(r.error.message);else load()}}
function catsTab(){$('bodyPanel').innerHTML=`<div class="panel"><h2>دسته‌بندی‌ها</h2>${cats.map(c=>`<div class="row"><b>${esc(c.name)}</b><div><button onclick="renameCat('${esc(c.id)}')">ویرایش</button><button class="danger" onclick="delCat('${esc(c.id)}')">حذف</button></div></div>`).join('')}<button class="primary" onclick="addCat()">+ دسته جدید</button></div>`}
async function addCat(){let n=prompt('نام دسته؟');if(n){let r=await sb.from('categories').insert({id:'c'+Date.now(),name:n,sort_order:cats.length+1});if(r.error)msg(r.error.message);else load()}}
async function renameCat(id){let c=cats.find(x=>x.id===id),n=prompt('نام جدید',c.name);if(n){let r=await sb.from('categories').update({name:n}).eq('id',id);if(r.error)msg(r.error.message);else load()}}
async function delCat(id){if(confirm('دسته حذف شود؟')){let r=await sb.from('categories').delete().eq('id',id);if(r.error)msg(r.error.message);else load()}}
function homeTab(){let h=settings.home||{};$('bodyPanel').innerHTML=`<div class="panel"><h2>صفحه اصلی</h2><label>متن کوچک<input id="hk" value="${esc(h.kicker)}"></label><label>عنوان<input id="ht" value="${esc(h.title)}"></label><label>توضیحات<textarea id="hx">${esc(h.text)}</textarea></label><label>متن دکمه<input id="hb" value="${esc(h.button)}</label><label>لینک/آدرس تصویر فعلی<input id="hu" value="${esc(h.hero)}</label><label>تصویر جدید<input id="hi" type="file" accept="image/*"></label><button class="primary" onclick="saveHome()">ذخیره</button></div>`}
async function saveHome(){let hero=$('hu').value;if($('hi').files[0])hero=await upload($('hi').files[0]);await saveSettings({home:{kicker:$('hk').value,title:$('ht').value,text:$('hx').value,button:$('hb').value,hero}});}
function brandTab(){let b=settings.brand||{};$('bodyPanel').innerHTML=`<div class="panel"><h2>مجموعه و لوگو</h2><label>نام<input id="bn" value="${esc(b.name)}"></label><div class="grid2"><label>تلفن<input id="bp" value="${esc(b.phone)}"></label><label>اینستاگرام<input id="bi" value="${esc(b.instagram)}"></label></div><label>آدرس<input id="ba" value="${esc(b.address)}"></label><label>ساعت کاری<input id="bh" value="${esc(b.hours)}"></label><label>لوگو فعلی / لینک<input id="blurl" value="${esc(b.logo)}"></label><label>آپلود لوگو<input id="bl" type="file" accept="image/*"></label><button class="primary" onclick="saveBrand()">ذخیره</button></div>`}
async function saveBrand(){let logo=$('blurl').value;if($('bl').files[0])logo=await upload($('bl').files[0]);await saveSettings({brand:{name:$('bn').value,phone:$('bp').value,instagram:$('bi').value,address:$('ba').value,hours:$('bh').value,logo}})}
function qrTab(){let q=settings.qr||{};$('bodyPanel').innerHTML=`<div class="panel"><h2>QR</h2><label>لینک منو<input id="qu" value="${esc(q.url||location.origin+'/index.html')}"></label><label>متن<input id="ql" value="${esc(q.label||'برای مشاهده منوی کافه جیگر اسکن کنید')}"></label><label>اندازه<input id="qs" type="number" value="${q.size||240}"></label><button class="primary" onclick="saveQR()">ذخیره</button></div>`}
async function saveQR(){await saveSettings({qr:{url:$('qu').value,label:$('ql').value,size:+$('qs').value||240}})}
function footerTab(){let f=settings.footer||{};$('bodyPanel').innerHTML=`<div class="panel"><h2>طراح و فوتر</h2><label>متن<input id="fd" value="${esc(f.designer)}"></label><label>لینک<input id="fl" value="${esc(f.link)}"></label><label><input id="fs" type="checkbox" ${f.show!==false?'checked':''}> نمایش</label><button class="primary" onclick="saveFooter()">ذخیره</button></div>`};async function saveFooter(){await saveSettings({footer:{designer:$('fd').value,link:$('fl').value,show:$('fs').checked}})}
function appearanceTab(){let a=settings.appearance||{};$('bodyPanel').innerHTML=`<div class="panel"><h2>ظاهر</h2><div class="grid2"><label>رنگ اصلی<input id="aa" type="color" value="${a.accent||'#d6a85b'}"></label><label>زمینه<input id="ab" type="color" value="${a.bg||'#090909'}"></label><label>کارت<input id="ac" type="color" value="${a.card||'#151515'}"></label><label>تیرگی هیرو %<input id="ad" type="number" value="${a.heroDark||88}"></label></div><button class="primary" onclick="saveAppearance()">ذخیره</button></div>`};async function saveAppearance(){await saveSettings({appearance:{accent:$('aa').value,bg:$('ab').value,card:$('ac').value,heroDark:+$('ad').value}})}
init();
