-- کافه جیگر | Supabase schema
create table if not exists public.site_settings (
  id bigint primary key default 1,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint site_settings_singleton check (id = 1)
);
create table if not exists public.categories (
  id text primary key,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id text references public.categories(id) on delete set null,
  description text default '',
  price numeric not null default 0,
  old_price numeric not null default 0,
  discount numeric not null default 0,
  image_url text default '',
  featured boolean not null default false,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.site_settings(id,data) values (1, '{
  "home":{"kicker":"CAFE • JIGAR","title":"کافه جیگر","text":"طعم خوب، فضای خاص و تجربه‌ای متفاوت","button":"مشاهده منو","hero":""},
  "brand":{"name":"کافه جیگر","phone":"","instagram":"","address":"","hours":"هر روز ۹ صبح تا ۱۲ شب","logo":""},
  "qr":{"url":"","label":"برای مشاهده منوی کافه جیگر اسکن کنید","size":240},
  "footer":{"designer":"Designed by CAFE JIGAR","link":"","show":true},
  "appearance":{"accent":"#d6a85b","bg":"#090909","card":"#151515","heroDark":88}
}'::jsonb)
on conflict (id) do nothing;
insert into public.categories(id,name,sort_order) values
('hot','نوشیدنی گرم',1),('cold','نوشیدنی سرد',2),('food','غذا و میان‌وعده',3),('dessert','دسر',4)
on conflict (id) do nothing;
insert into public.products(name,category_id,description,price,sort_order) values
('اسپرسو','hot','اسپرسوی کلاسیک کافه جیگر',85000,1),
('لاته','hot','اسپرسو با شیر بخار داده شده',125000,2),
('آیس لاته','cold','لاته خنک با یخ',145000,3)
;

alter table public.site_settings enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
create policy "public can read settings" on public.site_settings for select using (true);
create policy "public can read categories" on public.categories for select using (true);
create policy "public can read products" on public.products for select using (true);
create policy "authenticated can manage settings" on public.site_settings for all to authenticated using (true) with check (true);
create policy "authenticated can manage categories" on public.categories for all to authenticated using (true) with check (true);
create policy "authenticated can manage products" on public.products for all to authenticated using (true) with check (true);

insert into storage.buckets (id,name,public) values ('menu-images','menu-images',true) on conflict (id) do nothing;
create policy "public can view menu images" on storage.objects for select using (bucket_id='menu-images');
create policy "authenticated can upload menu images" on storage.objects for insert to authenticated with check (bucket_id='menu-images');
create policy "authenticated can update menu images" on storage.objects for update to authenticated using (bucket_id='menu-images') with check (bucket_id='menu-images');
create policy "authenticated can delete menu images" on storage.objects for delete to authenticated using (bucket_id='menu-images');
